Resources:
  CertificatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dynamodb.tableName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PrimaryKey
          AttributeType: S
      KeySchema:
        - AttributeName: PrimaryKey
          KeyType: HASH
